numeric_register_dependency(NetCDF)


if (NUMERIC_NetCDF_REQUIRE_DOWNLOAD)

  include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/dependencies/HDF5.cmake)

  if (NUMERIC_ENABLE_MPI)
    find_package(MPI REQUIRED COMPONENTS C)
    include_directories(${MPI_C_INCLUDE_PATH})
  endif()

  set(NETCDF_HDF5_PREFER_PARALLEL ${NUMERIC_ENABLE_MPI})
  set(NETCDF_BUILD_UTILITIES OFF)
  set(NETCDF_ENABLE_EXAMPLES OFF)
  set(NETCDF_ENABLE_TESTS OFF)
  set(NETCDF_HDF5_PARALLEL ${NUMERIC_ENABLE_MPI})
  set(NETCDF_ENABLE_HDF5 ON)
  set(NETCDF_ENABLE_PNETCDF OFF)
  set(NETCDF_ENABLE_PARALLEL ${NUMERIC_ENABLE_MPI})
  set(NETCDF_ENABLE_DAP OFF)
  set(NETCDF_ENABLE_DAP2 OFF)
  set(NETCDF_ENABLE_DAP4 OFF)

  FetchContent_Declare(
    NetCDF
    GIT_REPOSITORY https://github.com/Unidata/netcdf-c.git
    GIT_TAG v4.9.3-rc1
    GIT_PROGRESS ON
  )

  list(APPEND NUMERIC_DEPENDENCIES NetCDF)

endif()
