find_package(HIP REQUIRED)
message(STATUS "HIP = ${HIP}")
message(STATUS "REQUIRED_VARS = ${REQUIRED_VARS}")
message(STATUS "HIP_ROOT_DIR = ${HIP_ROOT_DIR}")
message(STATUS "HIP_HIPCC_EXECUTABLE = ${HIP_HIPCC_EXECUTABLE}")
message(STATUS "HIP_HIPCONFIG_EXECUTABLE = ${HIP_HIPCONFIG_EXECUTABLE}")
message(STATUS "HIP_PLATFORM = ${HIP_PLATFORM}")
message(STATUS "HIP_COMPILER = ${HIP_COMPILER}")
message(STATUS "HIP_RUNTIME = ${HIP_RUNTIME}")
message(STATUS "VERSION_VAR = ${VERSION_VAR}")
message(STATUS "HIP_VERSION = ${HIP_VERSION}")

set(HIP_INCLUDE_DIR ${HIP_ROOT_DIR}/../include)

add_library(hip INTERFACE)
target_compile_definitions(hip INTERFACE "-DNUMERIC_ENABLE_HIP")
target_include_directories(hip INTERFACE ${HIP_INCLUDE_DIR})
if(HIP_PLATFORM STREQUAL "amd")
  target_compile_definitions(hip INTERFACE __HIP_PLATFORM_AMD__)
  message(WARNING "No Optimization Flags set for AMD HIP")
elseif(HIP_PLATFORM STREQUAL "nvidia")
  find_package(CUDAToolkit REQUIRED)
  target_link_libraries(hip INTERFACE CUDA::cudart)
  target_link_libraries(hip INTERFACE CUDA::cuda_driver)
  target_link_libraries(hip INTERFACE CUDA::nvrtc)
  target_compile_definitions(hip INTERFACE __HIP_PLATFORM_NVIDIA__)
  if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -G")
  elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
    set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} --dopt=on -DNDEBUG")
  elseif(CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} --dopt=on -G -DNDEBUG")
  elseif(CMAKE_BUILD_TYPE STREQUAL "MinSizeRel")
    set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} --dopt=on -DNDEBUG")
  endif()
else()
  message(FATAL_ERROR "Unknown platform: ${HIP_PLATFORM}")
endif()
